# editor section
[editor]

editor_width=1920
editor_height=1080
editor_fullscreen=0
editor_vsync=0

editor_lock_frame_rate=0

#lock frame rate to this value
editor_fps=60

#max frame rate
editor_max_fps=170

editor_font_size=17.0

# Path: configs/MoerEngine.ini

[engine]

default_rhi=Vulkan
max_frame_in_flight=3