
#include "D3D12Device.h"
#include <WinPixEventRuntime/pix3.h>

namespace Moer::Render {

    namespace PIXCapturerDetail {

        struct PIXLibraryLoader {
            HMODULE handle_;

        public:
            PIXLibraryLoader() {
                handle_ = PIXLoadLatestWinPixGpuCapturerLibrary();  // have to install PIX app! may change to other way to directly load dll. https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK/blob/main/framework/cauldron/framework/src/core/framework.cpp#L287
            }
            //WARNING : WinPixGpuCapturer.dll was loaded after D3D12Core.dll.
            //This strongly implies that the application has loaded WinPixGpuCapturer.dll after creating a D3D12 device.
            //That D3D12 device, and any GPU work generated by its child objects, will not be captured by  PIX
            // so if want to capture, we have to load it before create device

            ~PIXLibraryLoader() {
                if (handle_) {
                    FreeLibrary(handle_);
                }
            }
        };

        struct PIXCapturer : public GPUCapturer {
            PIXCapturer() {
                static PIXCapturerDetail::PIXLibraryLoader libraryLoader;// lazy init
            }

            void Begin(const std::filesystem::path& outputFilename) override {
                std::string filename = outputFilename.filename().string();

                if (!filename.ends_with(".wpix")) {
                    filename += ".wpix";
                }

                filename = (outputFilename.parent_path() / filename).string();

                PIXCaptureParameters params{};
                const std::wstring   wfilename       = std::filesystem::path(filename).generic_wstring();
                params.GpuCaptureParameters.FileName = wfilename.c_str();
                DX_CHECK_HRESULT(PIXBeginCapture(PIX_CAPTURE_GPU, &params));
            }

            void End() override {
                DX_CHECK_HRESULT(PIXEndCapture(false));
            }
        };
    }// namespace PIXCapturerDetail

    UniquePtr<GPUCapturer> CreatePIXCapturer() {
        return MakeUnique<PIXCapturerDetail::PIXCapturer>();
    }
}// namespace Moer::Render

