#ifndef MOERENGINE_SHADER_RESOURCE_H
#define MOERENGINE_SHADER_RESOURCE_H
#include <cstdint>
#include <assert.h>
#include <memory>
#include <atomic>
#include <misc/CountableRef.h>
#include <misc/Hash.h>
#include <shared_mutex>
#include <unordered_map>
#include <vector>
#include "ShaderCommon.h"
#include "shader/ShaderCommon.h"

class ShaderResource : Countable {
public:
protected:
    void Destroy() override {
        delete this;
    }
};
// struct ShaderCodeSortKey {
//     std::string file_path;
//     std::string macro_definitions;
// };
struct ShaderEntry {
    //shader compiled code
    std::vector<uint8_t> code;
    EShaderType          type;
    //param info map generated by shader reflection
    ShaderParametersInfoMap param_info;
};
class ShaderCodeResourceMap {

public:
    void AddShaderCompilerOutput(std::string shader_sort_key, const ShaderCompilerOutput& _output);
    // int32_t                                      GetIndexByHash(const Hash64City& _hash);
    // Hash64City                                   resource_hash;
    // std::vector<Hash64City>                      shader_hashes;
    // std::vector<ShaderEntry>                     shader_entries;
    std::map<std::string, ShaderEntry> shader_code_entries;
    ShaderCodeResourceMap() {}
    ShaderCodeResourceMap(const ShaderCodeResourceMap& other) {}
    ShaderCodeResourceMap(ShaderCodeResourceMap&& other) {}

private:
    std::shared_mutex rw_mutex;
    // friend class ShaderResourceManager;
};

//for RHI shader creation
class ShaderMapResource : ShaderResource {
};

#endif//MOERENGINE_SHADER_RESOURCE_H
