#ifndef MOERENGINE_SHADER_RESOURCE_H
#define MOERENGINE_SHADER_RESOURCE_H
#include <cstdint>
#include <assert.h>
#include <atomic>
#include <misc/CountableRef.h>
#include <misc/Hash.h>
#include <mutex>
#include <shared_mutex>
#include "ShaderCommon.h"
#include "math/Constant.h"
#include "misc/STL.h"
#include "rhi/RHICommon.h"
#include "rhi/RHIResource.h"
#include "shader/Shader.h"
#include "shader/ShaderCommon.h"


class ShaderResource : Countable {
public:
protected:
    void Destroy() override {
        delete this;
    }
};

struct ShaderCodeEntry {
    //shader compiled code
    Moer::Array<uint8_t> code;
    EShaderType          type;
    //param info map generated by shader reflection
    ShaderParametersInfoMap param_info;
};

struct ShaderResourceKey {
    uint64_t         shader_name_hash;
    uint32_t         mutation_id;
};

inline bool operator==(const ShaderResourceKey& lhs, const ShaderResourceKey& rhs) {
    return lhs.shader_name_hash == rhs.shader_name_hash && lhs.mutation_id == rhs.mutation_id;
}

namespace std {
    template<>
    struct hash<ShaderResourceKey> {
        size_t operator()(const ShaderResourceKey& key) const {
            size_t hash = key.shader_name_hash;
            HashCombine(hash, key.mutation_id);
            return hash;
        }
    };
}// namespace std

//contains resources indirect index for a shader
struct ShaderResourceMapContent {
    using CodeIndex           = uint32_t;
    using RHIIndex            = uint32_t;
    uint32_t code_entry_index = ~0;
    uint32_t rhi_shader_index = ~0;

    bool ValidRHIShaderIndex() const {
        return rhi_shader_index != ~0;
    }

    bool ValidCodeEntryIndex() const {
        return code_entry_index != ~0;
    }
    // //indexes in shader code array
    // Moer::Array<CodeIndex> code_entries;
    // //indexes in rhi shader array
    // Moer::Array<RHIIndex> rhi_shaders;
    //pending for other resources
};

class ShaderResourceMap {
public:
    ShaderResourceMap();
    ~ShaderResourceMap();

    RHIShaderRef GetRHIShader(const ShaderResourceKey& key, const Shader* shader);

    void AddShaderCompilerOutput(ShaderResourceKey key, const ShaderCompilerOutput& _output);

private:
    Moer::UnorderedMap<ShaderResourceKey, ShaderResourceMapContent> shader_resource_map;

    Moer::Map<uint32_t, ShaderCodeEntry> shader_code_entries;
    Moer::Map<uint32_t, RHIShaderRef>    rhi_shaders;

    std::shared_mutex shader_code_entry_mutex;

    std::shared_mutex map_mutex;

    std::shared_mutex rhi_shader_mutex;
};

//for RHI shader creation
class ShaderTypeResourceMap {

public:
    ~ShaderTypeResourceMap();
    void AddShader(ShaderTypeKey type_name, Shader* shader);

    Shader* FindOrAddShader(ShaderTypeKey type_name, Shader* shader);

protected:
    friend class ShaderResourceManager;
    ShaderTypeResourceMap(EShaderPlatform platform);

protected:
    Moer::UnorderedMap<ShaderTypeKey, Shader*> shader_type_map;

    EShaderPlatform platform;

    std::shared_mutex shared_mutex;

private:
};

class ShaderResourceContent {
private:
    Moer::Array<Shader*> shaders;
};

#endif//MOERENGINE_SHADER_RESOURCE_H
